on:
  push:
    tags:
      - "v*"

name: Create Release

jobs:
  nuget:
    name: Publish Nuget
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.x
      - name: Pack
        run: dotnet pack --include-symbols  -o ./pkg ${{ github.ref }}
      - name: Push
        working-directory: ./pkg
        run: dotnet nuget push -k ${{secrets.NUGET_KEY}}
  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: nuget
    steps:
      - name: Create Release Notes
        uses: actions/github-script@v4.0.2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.request(`POST /repos/${{ github.repository }}/releases`, {
              tag_name: "${{ github.ref }}",
              generate_release_notes: true
            });
