on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

name: Create Release

jobs:
  nuget:
    name: Publish Nuget
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.x      
      - name: Pack
        run: dotnet pack --include-symbols --include-source -o ./pkg --version-suffix ${{ steps.get_version.outputs.VERSION }}
      - name: Push       
        run: | 
            cd ./pkg
            ls -l 
            dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_KEY}}
  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: nuget
    steps:
      - name: Create Release Notes
        uses: actions/github-script@v4.0.2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.request(`POST /repos/${{ github.repository }}/releases`, {
              tag_name: "${{ github.ref }}",
              generate_release_notes: true
            });
